# Generated by Django 5.0.4 on 2025-11-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_rename_especialidades_especialidade_and_more'),
        ('paciente', '0003_alter_consulta_data_aberta_alter_consulta_paciente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasAbertas',
        ),
    ]
